### PR TITLE
christopher/add fascn

### PR DESCRIPTION
**Pull request by christopherL91**
- **Update documentation**
- **Update typings**
- **Add dependency bitarray for FASC-N**
- **Add support for generating FASC-N**
- **Add tests for FASC-N**

### CODE REVIEW

**Comment by christopherL91** [comment]
I found some typings errors in the code. I could move those commits out of this PR if you'd like.

**Comment by christopherL91** [comment]
The module name is not set in stone, as there's already a piv.py it felt weird to have a module called the same. We could also discuss appropriate error handling and assertion that the lenght of each field are correct.

**Comment by chrismeyer-yubico** [comment]
just checking if there is any progress on this PR?

**Comment by dainnilsson** [comment]
No updates.

**Comment by dainnilsson** [comment]
Replaced by #628

**Pull request closed without merging**
