### PR TITLE
Add OTP HID support for FreeBSD

### PR DESCRIPTION
**Pull request by grembo**
This supports the default uhid(4) and the new hidraw(4) driver.

While not a dependency, https://github.com/Yubico/python-fido2/pull/139
will help to fully unbreak FreeBSD support.

### CODE REVIEW

**Comment by grembo** [comment]
@dainnilsson Hoping that you can help here - if possible, could you please approve running the remaining workflows?

**Comment by dainnilsson** [comment]
Sorry, I thought I had already approved it.

Regarding the PR, I've had a quick look and everything looks fine. I do want to spend a little more time testing it out and unfortunately haven't had time to do so yet, sorry for the delay!

**Comment by grembo** [comment]
@dainnilsson Thank you. As far as I can see both problems are in the CI procedures (windows has some issue with PyInstaller and ubuntu can't run black).

The one issue all of this has (just like with python-fido2) is that - by default - the kbd driver attaches to the HID used by OTP (so otp commands won't work).

The workaround is (again):

```
DEV=$(usbconfig | grep Yubico | cut -d: -f1)
usbconfig $DEV power_off
usbconfig $DEV add_quirk UQ_KBD_IGNORE
usbconfig $DEV power_on
```

Maybe I can add something in the future that does this automatically when communicating with the key - I would have to check with the FreeBSD USB folks first though and I think this is already quite an improvement over not being able to use it at all.

**Comment by grembo** [comment]
Hi @dainnilsson,

> The one issue all of this has (just like with python-fido2) is that - by default - the kbd driver attaches to the HID used by OTP (so otp commands won't work).

I figured out how to make this work with hidraw(4) in a non-intrusive way (so YubiKey Manager itself won't contain anything wicked):

```
sysrc kld_list+="hidraw hkbd"
cat >>/boot/loader.conf<<EOF
hw.usb.usbhid.enable="1"
hw.usb.quirk.0="0x1050 0x0010 0 0xffff UQ_KBD_IGNORE"  # YKS_OTP
hw.usb.quirk.1="0x1050 0x0110 0 0xffff UQ_KBD_IGNORE"  # NEO_OTP
hw.usb.quirk.2="0x1050 0x0111 0 0xffff UQ_KBD_IGNORE"  # NEO_OTP_CCID
hw.usb.quirk.3="0x1050 0x0114 0 0xffff UQ_KBD_IGNORE"  # NEO_OTP_FIDO
hw.usb.quirk.4="0x1050 0x0116 0 0xffff UQ_KBD_IGNORE"  # NEO_OTP_FIDO_CCID
hw.usb.quirk.5="0x1050 0x0401 0 0xffff UQ_KBD_IGNORE"  # YK4_OTP
hw.usb.quirk.6="0x1050 0x0403 0 0xffff UQ_KBD_IGNORE"  # YK4_OTP_FIDO
hw.usb.quirk.7="0x1050 0x0405 0 0xffff UQ_KBD_IGNORE"  # YK4_OTP_CCID
hw.usb.quirk.8="0x1050 0x0410 0 0xffff UQ_KBD_IGNORE"  # YKP_OTP_FIDO
EOF
reboot
```

I also added some documentation to README.adoc, hoping that it won't take too much room there, as it seemed a more natural place than the sources. Please let me know if this is TMI.

p.s. Seems like each iteration of the code needs a fresh approval.

**Comment by grembo** [comment]
@dainnilsson Please note that build failures are due to CI problems, I opened #507 to address these separately.

**Comment by dainnilsson** [comment]
Can you re-target this PR onto the `next` branch instead of `main`? I believe these build issues should already be solved there. We will be merging the changes in `next` back into `main` shortly. Currently `main` is quite outdated.

**Comment by grembo** [comment]
@dainnilsson changed the base to `next`, but, probably due to being a first time contributor, this only triggered a rerun of "LGTM analysis".

**Comment by dainnilsson** [comment]
I manually restarted some builds now, but looks like it's still failing. Please just ignore these for now, I'll make sure the build works later.

**Comment by grembo** [comment]
Seems like builds failed with the same errors again - I can't verify if the new base was taken into account though (maybe you can?). I'll do a force push to trigger a fresh rebuild to be certain.

**Comment by grembo** [comment]
Seems like that did the trick, thanks

**Comment by grembo** [comment]
Cool, thanks for being super responsive!

**Comment by dainnilsson** [comment]
I attempted a command line merge --squash for this (to be able to sign with my YubiKey) which made a fine commit, but Github unfortunately doesn't detect the connection to this PR :/

Anyway, this is now merged in ecd7897.

**Comment by grembo** [comment]
Thanks

**Pull request closed without merging**
